/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchCountryRouteImport } from './routes/search.$country'
import { Route as LocationSlugRouteImport } from './routes/location.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchCountryRoute = SearchCountryRouteImport.update({
  id: '/search/$country',
  path: '/search/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSlugRoute = LocationSlugRouteImport.update({
  id: '/location/$slug',
  path: '/location/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/location/$slug': typeof LocationSlugRoute
  '/search/$country': typeof SearchCountryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/location/$slug': typeof LocationSlugRoute
  '/search/$country': typeof SearchCountryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/location/$slug': typeof LocationSlugRoute
  '/search/$country': typeof SearchCountryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/location/$slug' | '/search/$country'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/location/$slug' | '/search/$country'
  id: '__root__' | '/' | '/location/$slug' | '/search/$country'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationSlugRoute: typeof LocationSlugRoute
  SearchCountryRoute: typeof SearchCountryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$country': {
      id: '/search/$country'
      path: '/search/$country'
      fullPath: '/search/$country'
      preLoaderRoute: typeof SearchCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$slug': {
      id: '/location/$slug'
      path: '/location/$slug'
      fullPath: '/location/$slug'
      preLoaderRoute: typeof LocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationSlugRoute: LocationSlugRoute,
  SearchCountryRoute: SearchCountryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
